# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'UnityWithCameraKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnityWithCameraKit

  pod 'Alamofire', '~> 5.4'
  pod 'SCSDKCameraKit', '1.26.1'
  pod 'SCSDKCameraKitReferenceUI', '1.26.1'
  pod 'SCSDKCameraKitReferenceSwiftUI', '1.26.1'
  
  target 'UnityWithCameraKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnityWithCameraKitUITests' do
    # Pods for testing
  end

end
