# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'UnitySwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UnitySwift

  pod 'Alamofire', '~> 5.4'
  pod 'SCSDKCameraKit', '1.23.0'
	pod 'SCSDKCameraKitReferenceUI', '1.23.0'
	pod 'SCSDKCameraKitReferenceSwiftUI', '1.23.0'
  
  target 'UnitySwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UnitySwiftUITests' do
    # Pods for testing
  end

end
