on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]


jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello, thank you for your response. We are enthusiastic about receiving contributions from our community. If your issue/comment requires support, please see the [Camera Kit Community Forum](https://community.snap.com/snapar/categories/camera-kit) for support as support requests on this repo will be closed out. Code contributions will be reviewed regularly. Thank you!"
          pr-message: "Thank you for contributing to this project, your support is much appreciated. A member of our team will be reviewing your contribution soon"
          footer: ""
